language: android
dist: trusty
os: linux
jdk: oraclejdk8

env:
  global:
    - secure: "XW/4CwrBZhYhPTw4wgvasNQojyoR58VibMC7pj2Tgwp2kNm+h0CuD7JNkHx9eCSfUTJ3oPcO4nKP2doXf/Ty22iJ6CfRkfp4jYIgO+hhex52cUPMAWEiuQho/HiyLVrjx0nV3rpUE5bW0qe1c5CHkTaDJMvxWe533sKcw19Jv2BaUfGLRUhAiFoLmj1DQt09fHOkPQ1fgf0s2Vs/4WsKErkyti23+XU/HyhxXNdrSqqQAPzJK5McoCGVpVxQgdai/FFJb9KNyfaomLzfH955qHZWj08TvKfvFfcVfwQyNAEx/0m9BAvoeGDOFJVqaQNapPgnk2zSDyZTPUePiyK+KA8FvHqw5u2Q/eM9RDQCHYR0+N3SzPZLw+PDNYzUXIT20I4Oepy8+cX5zK40rRWKYKz1skE8sSTyaa9qQHFdbbJImxqsSEwftnFhiJ8DLi3opcnij4LCP7aQRbTlt1v1mggFIrovYLF8rckuowexrmEhCO1AlcFqecH3gJVV65A0SgMwD/f7lntp94W4EhCw3QKxanNlLBc9GwSqvDVVW/qM72+DTHTar5me+ycpadsMxq8GF1UFLg3JdFOhwXSM3eyk9PxFY1ytyHvr6pzQVPEHhQ5cnbhNp85gMHrCTClTApp6Kk/yX4W+vEiidjFjqHEiet+eQa4sm1j2uCsvZ/0="
    - secure: "PHzPxBUfK5szOUrXhkBfb4HJB0ru5F1gb3aTXa/xY3VtNYEetysijRrujKrOzGbzZWjNR7fIMM81/Op4G35wP6k6f1q8mrThQCUPo/cUmLfXubi5hbJ8shyQLWuZxRJGepmUohi1jMa3Vs5JWjlZSN8AHwCTjXpFSYTugIRI3wYd1BQfgcg3mIsgOh+xkc7hp9ywiN0exL9fsavM6HXCixh67sIez09rMefuZ+GxELvtvrCELKWM9RecuOaqnPkd3+PpFyBC164fIlnWKtIa/JA4vXQdW3/SJb9w0NdWvLWHTN4odhhaS/kFR6bx+wq7GzXOA5xJNlP7PG2ViIaL13ESZuvgw8EBWVvN7PC5IJKyoKsF0xk3L2uNG1wWepjef8Z854DPv5SQDfcdw7vNKDutzniHji+kZocRMvt43cBTeengpgyuTCDzSE50TDEPzDtRc9Wo+n6Hv5Y1qJ8Uclwr42ihExEWznPJOz6LRv1kB62b+VRWjO8IyiKidc5FgPe3iL6ONVKwik1+m7607AkrwZT7XDpPEofPIgGv4Pt7c8xDMMAmBu9HTbY1qHuWtawRPZKPl/dTtq8yxc2nOrkJ4Hurt97+C4TWzcYl5e6e5JjL8oegSgdzVB7Ep0iOMWzfwy8s+t/VaV3A5zdmpickYoPVH5uRo6TjmZOKnwA="

before_install:
  # Install SDK license so Android Gradle plugin can install dependencies
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$ANDROID_HOME/licenses/android-sdk-license"

install: ./gradlew assemble --stacktrace

script: ./gradlew test --stacktrace

before_deploy:
  - echo "gradle.publish.key=$GRADLE_PUBLISH_KEY" >> $HOME/.gradle/gradle.properties
  - echo "gradle.publish.secret=$GRADLE_PUBLISH_SECRET" >> $HOME/.gradle/gradle.properties

deploy:
  provider: script
  script: ./gradlew publishPlugins
  on:
    tags: true
  edge: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
