name: Publish

on:
  push:
    tags: '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Gradle plugin portal credentials
        run: |
          echo "gradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}" >> $HOME/.gradle/gradle.properties
          echo "gradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}" >> $HOME/.gradle/gradle.properties

      - name: Publish plugin
        run: ./gradlew publishPlugins --stacktrace
