name: Run Tests

on:
  push:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'

      - name: Create jar
        run: ./gradlew jar

      - name: Publish to MavenLocal
        run: ./gradlew publishToMavenLocal

      - name: Run tests
        run: ./gradlew test
